name: Deploy to proxmox lxc
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Node.js CI
    types:
      - completed
    branches:
      - main
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }} 
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Checkout to repo
        uses: actions/checkout@v5
      - name: Set up SSH directory and known_hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts # Ensure correct permissions
      - name: Copy Files to LXC
        run: |
          ssh-keyscan ${{ vars.PROXMOX_CHATBOT_WEBSITE_LXC_TAILSCALE_NAME }} >> ~/.ssh/known_hosts
          rsync -avz --delete --exclude='.git' --exclude='node_modules' --exclude='.github' --exclude=".tmp" ./ root@${{ vars.PROXMOX_CHATBOT_WEBSITE_LXC_TAILSCALE_NAME }}:/home/app
