name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-reusable-build:
    uses: ./.github/workflows/lint_and_unit_tests.yaml
    with:
      node-version: '22.18'